In [65]:
import json,csv
from kafka import KafkaProducer
import time

KAFKA_BOOTSTRAP_SERVERS = 'localhost:9092'

def producer(file):
    producer = KafkaProducer( bootstrap_servers=KAFKA_BOOTSTRAP_SERVERS,
                               value_serializer=lambda v: json.dumps(v).encode('utf-8'))
    path ='/home/hilario/PoD/2ndSemester/MAPD-B/Data-processing/Labs/kafka_pazzini/notebooks/Taxi_NY/Data/'
    with open(path+file+'.csv') as file:
        reader = csv.DictReader(file, delimiter=",")
        for row in reader:
            row["HEAD"] = int(row["HEAD"])
            row["FPGA"] = int(row["FPGA"])
            row["TDC_CHANNEL"] = int(row["TDC_CHANNEL"])
            row["ORBIT_CNT"] = float(row["ORBIT_CNT"])
            row["BX_COUNTER"] = int(row["BX_COUNTER"])
            row["TDC_MEAS"] = float(row["TDC_MEAS"])
            producer.send(topic='Experiment_measurements', value=row)
            #producer.send(topic='Experiment_measurements', value=json.dumps(row))
            producer.flush()

for i in ['test_3'] :
    print(i)
    producer(i)
    time.sleep(0.25)

test_3


In [18]:
a=[[53, 5], [34, 1], [27, 1], [44, 5], [12, 3], [47, 4], [52, 1], [16, 2], [6, 1], [20, 1], [40, 1], [48, 3], [5, 1], [19, 3], [41, 2], [15, 2], [43, 2], [61, 1], [17, 1], [59, 1], [55, 1], [4, 1], [23, 2], [39, 1], [49, 2], [7, 2], [63, 1], [50, 1], [45, 5], [25, 2], [24, 1], [62, 2], [21, 2], [60, 1], [56, 1], [58, 1], [14, 1], [42, 3], [30, 1], [46, 4], [0, 2], [18, 2]]

In [33]:
a

[[53, 5],
 [34, 1],
 [27, 1],
 [44, 5],
 [12, 3],
 [47, 4],
 [52, 1],
 [16, 2],
 [6, 1],
 [20, 1],
 [40, 1],
 [48, 3],
 [5, 1],
 [19, 3],
 [41, 2],
 [15, 2],
 [43, 2],
 [61, 1],
 [17, 1],
 [59, 1],
 [55, 1],
 [4, 1],
 [23, 2],
 [39, 1],
 [49, 2],
 [7, 2],
 [63, 1],
 [50, 1],
 [45, 5],
 [25, 2],
 [24, 1],
 [62, 2],
 [21, 2],
 [60, 1],
 [56, 1],
 [58, 1],
 [14, 1],
 [42, 3],
 [30, 1],
 [46, 4],
 [0, 2],
 [18, 2]]

In [31]:
import numpy as np

In [52]:
b = np.array(a)

In [53]:
b[:,0]

array([53, 34, 27, 44, 12, 47, 52, 16,  6, 20, 40, 48,  5, 19, 41, 15, 43,
       61, 17, 59, 55,  4, 23, 39, 49,  7, 63, 50, 45, 25, 24, 62, 21, 60,
       56, 58, 14, 42, 30, 46,  0, 18])

In [54]:
b[:,1]

array([5, 1, 1, 5, 3, 4, 1, 2, 1, 1, 1, 3, 1, 3, 2, 2, 2, 1, 1, 1, 1, 1,
       2, 1, 2, 2, 1, 1, 5, 2, 1, 2, 2, 1, 1, 1, 1, 3, 1, 4, 2, 2])

In [55]:
b

array([[53,  5],
       [34,  1],
       [27,  1],
       [44,  5],
       [12,  3],
       [47,  4],
       [52,  1],
       [16,  2],
       [ 6,  1],
       [20,  1],
       [40,  1],
       [48,  3],
       [ 5,  1],
       [19,  3],
       [41,  2],
       [15,  2],
       [43,  2],
       [61,  1],
       [17,  1],
       [59,  1],
       [55,  1],
       [ 4,  1],
       [23,  2],
       [39,  1],
       [49,  2],
       [ 7,  2],
       [63,  1],
       [50,  1],
       [45,  5],
       [25,  2],
       [24,  1],
       [62,  2],
       [21,  2],
       [60,  1],
       [56,  1],
       [58,  1],
       [14,  1],
       [42,  3],
       [30,  1],
       [46,  4],
       [ 0,  2],
       [18,  2]])

In [51]:
b[b[:, 0].argsort()]

array([[ 0,  2],
       [ 4,  1],
       [ 5,  1],
       [ 6,  1],
       [ 7,  2],
       [12,  3],
       [14,  1],
       [15,  2],
       [16,  2],
       [17,  1],
       [18,  2],
       [19,  3],
       [20,  1],
       [21,  2],
       [23,  2],
       [24,  1],
       [25,  2],
       [27,  1],
       [30,  1],
       [34,  1],
       [39,  1],
       [40,  1],
       [41,  2],
       [42,  3],
       [43,  2],
       [44,  5],
       [45,  5],
       [46,  4],
       [47,  4],
       [48,  3],
       [49,  2],
       [50,  1],
       [52,  1],
       [53,  5],
       [55,  1],
       [56,  1],
       [58,  1],
       [59,  1],
       [60,  1],
       [61,  1],
       [62,  2],
       [63,  1]])